---
driver:
  name: vagrant

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: ubuntu-14.04
    driver:
      require_chef_omnibus: 12.6.0
#  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[webserver::default]
    attributes:
